package com.cdc.ecommerce.model;

import java.math.BigDecimal;
import java.util.Date;

public class Toilet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.pk_id
     *
     * @mbg.generated
     */
    private Long pkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.longitude
     *
     * @mbg.generated
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.latitude
     *
     * @mbg.generated
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.check_status
     *
     * @mbg.generated
     */
    private Boolean checkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.picture_url
     *
     * @mbg.generated
     */
    private String pictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.label
     *
     * @mbg.generated
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.fix_status
     *
     * @mbg.generated
     */
    private Boolean fixStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.delete_status
     *
     * @mbg.generated
     */
    private Boolean deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.score
     *
     * @mbg.generated
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.like_number
     *
     * @mbg.generated
     */
    private Long likeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toilet.publisher
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.pk_id
     *
     * @return the value of toilet.pk_id
     *
     * @mbg.generated
     */
    public Long getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.pk_id
     *
     * @param pkId the value for toilet.pk_id
     *
     * @mbg.generated
     */
    public void setPkId(Long pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.address
     *
     * @return the value of toilet.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.address
     *
     * @param address the value for toilet.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.longitude
     *
     * @return the value of toilet.longitude
     *
     * @mbg.generated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.longitude
     *
     * @param longitude the value for toilet.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.latitude
     *
     * @return the value of toilet.latitude
     *
     * @mbg.generated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.latitude
     *
     * @param latitude the value for toilet.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.check_status
     *
     * @return the value of toilet.check_status
     *
     * @mbg.generated
     */
    public Boolean getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.check_status
     *
     * @param checkStatus the value for toilet.check_status
     *
     * @mbg.generated
     */
    public void setCheckStatus(Boolean checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.description
     *
     * @return the value of toilet.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.description
     *
     * @param description the value for toilet.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.picture_url
     *
     * @return the value of toilet.picture_url
     *
     * @mbg.generated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.picture_url
     *
     * @param pictureUrl the value for toilet.picture_url
     *
     * @mbg.generated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.label
     *
     * @return the value of toilet.label
     *
     * @mbg.generated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.label
     *
     * @param label the value for toilet.label
     *
     * @mbg.generated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.fix_status
     *
     * @return the value of toilet.fix_status
     *
     * @mbg.generated
     */
    public Boolean getFixStatus() {
        return fixStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.fix_status
     *
     * @param fixStatus the value for toilet.fix_status
     *
     * @mbg.generated
     */
    public void setFixStatus(Boolean fixStatus) {
        this.fixStatus = fixStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.delete_status
     *
     * @return the value of toilet.delete_status
     *
     * @mbg.generated
     */
    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.delete_status
     *
     * @param deleteStatus the value for toilet.delete_status
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.create_time
     *
     * @return the value of toilet.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.create_time
     *
     * @param createTime the value for toilet.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.modify_time
     *
     * @return the value of toilet.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.modify_time
     *
     * @param modifyTime the value for toilet.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.score
     *
     * @return the value of toilet.score
     *
     * @mbg.generated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.score
     *
     * @param score the value for toilet.score
     *
     * @mbg.generated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.like_number
     *
     * @return the value of toilet.like_number
     *
     * @mbg.generated
     */
    public Long getLikeNumber() {
        return likeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.like_number
     *
     * @param likeNumber the value for toilet.like_number
     *
     * @mbg.generated
     */
    public void setLikeNumber(Long likeNumber) {
        this.likeNumber = likeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toilet.publisher
     *
     * @return the value of toilet.publisher
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toilet.publisher
     *
     * @param publisher the value for toilet.publisher
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }
}